version: 0.2
env:
  variables:
    AWS_REGION: "us-east-1"
    EKS_CLUSTER: "netflix-app-eks"
    # ECR_REPO: "266735826560.dkr.ecr.us-east-1.amazonaws.com/devsecops/netflix-app"
    # SONAR_HOST_URL: "http://34.232.189.92:9000"
    SONAR_PROJECT_KEY: "Netflix-app"
    # TRIVY_SERVER: "http://34.232.189.92:4954"
    SONAR_SCANNER_VERSION: "5.0.1.3000"
    
    # CÁC BIẾN CẦN THIẾT CHO GCP (Phải được thiết lập trong CodeBuild UI)
    GCP_REGION: "us-central1" # Đã sửa để khớp với Artifact Registry
    # GCP_ARTIFACT_HOST: "us-east1-docker.pkg.dev"
    # GKE_CLUSTER: "netflix-app-gke"
    K8S_NAMESPACE: "default"
    # GCP_PROJECT: "calm-cairn-455503-d0"
    # Cần set GCP_PROJECT (PLAIN TEXT)
    # Cần set DOCKER_CREDS_ARN & GCP_SA_KEY_ARN (SECRETS MANAGER)

phases:
  install:
    commands:
      - echo "🔧 Installing tools and dependencies..."
      - echo "🔧 Installing tools and dependencies... ${DOCKER_CREDS_ARN}"


      - echo Installing kubectl
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo Installing gke-gcloud-auth-plugin
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/gke-gcloud-auth-plugin"
      - chmod +x gke-gcloud-auth-plugin
      - mv gke-gcloud-auth-plugin /usr/local/bin/
      # Install jq và unzip
      - dnf install -y jq unzip curl unzip python3-pip zip
      # # Cài đặt Sonar Scanner
      - echo "Installing Sonar Scanner version ${SONAR_SCANNER_VERSION}..."
      - curl -fsLR --retry 5 https://github.com/SonarSource/sonar-scanner-cli/releases/download/${SONAR_SCANNER_VERSION}/sonar-scanner-cli-${SONAR_SCANNER_VERSION}-linux.zip -o scanner.zip
      - unzip scanner.zip -d /opt/
      - mv /opt/sonar-scanner-${SONAR_SCANNER_VERSION}-linux /opt/sonar-scanner 
      - export PATH=$PATH:/opt/sonar-scanner/bin
      
      # Cài đặt Google Cloud CLI (gcloud) - Dành cho AL2
      - echo "Installing Google Cloud CLI..."
      - curl -sSL https://sdk.cloud.google.com | bash
      - export PATH=$PATH:/root/google-cloud-sdk/bin
      - gcloud version
      - gcloud components install gke-gcloud-auth-plugin
      # # Install Trivy client
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      
      # IaC security: tfsec & checkov
      - pip install --quiet checkov tfsec

  pre_build:
    commands:
      - echo "🔐 Starting pre-build tasks..."
      - TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo "Using TAG = $TAG"
      
      # 1. Login ECR
      - echo "🔐 Logging into ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

      # 2. ĐĂNG NHẬP DOCKER HUB (Sử dụng Secrets Manager)
      - |
        echo "DEBUG: DOCKER_CREDS_ARN value is: '${DOCKER_CREDS_ARN}'"
        if [ -n "${DOCKER_CREDS_ARN}" ]; then
          echo "🐳 Logging into Docker Hub..."
          DOCKER_CREDS=$(aws secretsmanager get-secret-value --secret-id "${DOCKER_CREDS_ARN}" --query SecretString --output text)
          DOCKER_USER="thanhlam2k4"
          DOCKER_PASS=$(echo "$DOCKER_CREDS" | jq -r '.thanhlam2k4')
          if [ -z "$DOCKER_PASS" ]; then
            echo "❌ ERROR: Failed to parse Docker PAT from secret"
            exit 1
          fi
          echo "🔐 Logging into Docker Hub as: $DOCKER_USER"
          echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
        fi
      # 3. XÁC THỰC VÀ ĐĂNG NHẬP DOCKER VỚI GCP ARTIFACT REGISTRY
      - |
        if [ -n "$GCP_SA_KEY_ARN" ]; then
          echo "Fetching and extracting GCP service account key..."
          aws secretsmanager get-secret-value --secret-id "$GCP_SA_KEY_ARN" --query SecretString --output text \
            | jq -r '.gcp_sa_key' > /tmp/gcpkey.json \
          && gcloud auth activate-service-account --key-file=/tmp/gcpkey.json \
          && gcloud auth configure-docker $GCP_ARTIFACT_HOST --quiet;
        else
          echo "GCP_SA_KEY_ARN is empty, skipping GCP auth";
        fi

  build:
    commands:
      - echo "🔍 Running SonarQube scan..."
      - sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
      
      - echo "🐳 Building Docker image..."
      - docker build --platform linux/amd64 -t ${ECR_REPO}:$TAG . # Đã sửa lỗi tag image
      - docker tag ${ECR_REPO}:$TAG ${ECR_REPO}:latest # Tag cục bộ để scan

      - echo "🔎 Scanning image via Trivy..."
      # Kích hoạt Trivy scan (sẽ FAIL pipeline nếu có HIGH/CRITICAL)
      - trivy image --exit-code 1 --severity HIGH,CRITICAL ${ECR_REPO}:$TAG 

      - echo "🛡 Running IaC Security Scans..."
      # Lưu ý: Sẽ không fail build nếu chỉ có warning (do || true)
      - tfsec ./ || true 
      - checkov -d ./ || true
      
  post_build:
    commands:
      # 1. PUSH TO ECR (PRIMARY)
      - echo "📤 Pushing image to ECR..."
      - docker push ${ECR_REPO}:$TAG
      - docker push ${ECR_REPO}:latest # Đảm bảo tag latest luôn cập nhật

      # 2. MIRROR TO GCP ARTIFACT REGISTRY (STANDBY)
      - |
        if [ -n "$GCP_SA_KEY_ARN" ]; then
          echo "Mirroring image to GCP Artifact Registry..."
          # Đẩy image lên Artifact Registry
          docker tag ${ECR_REPO}:$TAG ${GCP_ARTIFACT_HOST}/${GCP_PROJECT}/netflix-clone/netflix-clone:$TAG
          docker push ${GCP_ARTIFACT_HOST}/${GCP_PROJECT}/netflix-clone/netflix-clone:$TAG
        fi
      
      # 3. DEPLOY TO EKS (PRIMARY)
      - echo "🚀 Deploying to EKS cluster (AWS Primary)..."
      #- aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER
      # - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER 
      # - kubectl config current-context
      # - aws sts get-caller-identity
      # - kubectl config view
      # - kubectl get nodes
      # - kubectl set image deployment/netflix-app-deployment netflix-container=${ECR_REPO}:$TAG -n $K8S_NAMESPACE
      # - kubectl rollout status deployment/netflix-app-deployment -n $K8S_NAMESPACE

      # 4. DEPLOY TO GKE (HOT STANDBY)
      - |
        if [ -n "$GCP_SA_KEY_ARN" ]; then
          echo "Deploying to GKE cluster (GCP Hot Standby)..."
          # Lấy thông tin xác thực cho kubectl
          gcloud container clusters get-credentials $GKE_CLUSTER --region $GCP_REGION --project $GCP_PROJECT
          
          # Triển khai (Sử dụng Image từ GCP Artifact Registry)
          kubectl set image deployment/netflix-app-deployment netflix-container=${GCP_ARTIFACT_HOST}/${GCP_PROJECT}/netflix-clone/netflix-clone:$TAG -n $K8S_NAMESPACE
          kubectl rollout status deployment/netflix-app-deployment -n $K8S_NAMESPACE
        fi
      
artifacts:
  files:
    - '**/*'
